modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="create_pyrotechnics"
version="1.0.0"
displayName="create: pyrotechnics"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="mharrysson, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_pyrotechnics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.create_pyrotechnics]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_pyrotechnics]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration